### ISSUE TITLE
12/24 hour setting

### ISSUE THREAD

**Issue by michapersson** [neverweep/xMoreTimeText#5]
Hi!

**_FIXED!**_

On my Nexus 7 (2013) my clock shows the time in 24 hours format, but on my Nexus 5 it shows 12 hour format after installing xMoreTimeText, all settings are the same on the devices. Been trying to change in Androids own settings, but with no succes. The only changes I've made is to show seconds, btw.

**_EDIT: Never mind, after another couple of reboots it's working!**_

/Micha

**Comment by neverweep** [comment]
Thanks for your report. There are still some problems in this module, I will work on this.
